### ISSUE TITLE
python 3.x support

### ISSUE THREAD

**Issue by auvipy** [kaustavdm/pyAvroPhonetic#5]
I would like to start work to port this on python 3 too. Should python 2 and 3 support should exist? will start after your inputs.

**Comment by kaustavdm** [comment]
I really have not done anything with this in a long while and I have no plans to do anything at the moment or in near future.

Get started if you want to improve this project. Feel free to fork and start your changes.

**Comment by auvipy** [comment]
I already forked and tried localy on my machine. will you accept PR?

**Comment by kaustavdm** [comment]
@auvipy I can, but I would recommend you to maintain your fork because I have no plans of managing this project. If you want to maintain it, I can put up a notice in the README pointing to your fork.

**Comment by auvipy** [comment]
then you can hand over :)

**Comment by kaustavdm** [comment]
Done. I've put up a notice in 26b7d56 pointing to your fork. Good luck!
